server:
  port: 8080 # Web ç«¯å£

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # ğŸ‘ˆ åŠ ä¸Šè¿™ä¸€è¡Œï¼Œè§£å†³ Swagger å¯åŠ¨æŠ¥é”™
  datasource:
    # ç¡®ä¿ä½ æœ¬åœ°å®‰è£…äº†MySQLï¼Œå¹¶ä¸”åˆ›å»ºäº†åä¸º simple_im çš„æ•°æ®åº“
    url: jdbc:mysql://localhost:3306/simple_im?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root        # ä½ çš„æ•°æ®åº“è´¦å·
    password: 123456 # â—â—è¿™é‡Œæ”¹æˆä½ çš„æ•°æ®åº“å¯†ç â—â—
    driver-class-name: com.mysql.cj.jdbc.Driver

# Netty é…ç½®
netty:
  port: 8888  # WebSocket ç«¯å£
  url: /im
#mybatis-plusé…ç½®
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # æ§åˆ¶å°æ‰“å°SQL
  global-config:
    db-config:
      id-type: auto  # ä¸»é”®ç­–ç•¥

# æ—¥å¿—é…ç½®
logging:
  level:
    # è®¾ç½®æˆ‘ä»¬çš„mapperæ¥å£ä¸ºDEBUGï¼Œè¿™æ ·ä¼šæ‰“å°SQLè¯­å¥
    com.shixun.simpleimserver.mapper: debug
    # è®¾ç½®MyBatisçš„æ ¸å¿ƒåŒ…ä¸ºWARNï¼Œè¿™æ ·å°±ä¸ä¼šæ‰“å°è¿æ¥ä¿¡æ¯ç­‰
    org.apache.ibatis: warn
    # è®¾ç½®Springçš„JDBCåŒ…ä¸ºWARN
    org.springframework.jdbc: warn